### ISSUE TITLE
메인서버와 딥러닝 서버 간 오류코드 정의

### ISSUE THREAD

**Issue by YongSiHun** [KNUT-Capstone-Design-team-1/main-server-v2#4]
## 계획
* 딥러닝 서버와 메인 서버 간 통신에서 errCode 라는 키로 내려올 코드를 정의
  - 예시
```
// 알약 인식 실패
{ isSuccess: false, errCode: 'recognition.pill.not-protected' }
```

## Convention
* 큰범주.중간범주.작은범주.세부범주

## 오류 상황 정의
* 딥러닝 서버 응답 없음 
  - 메인 서버 내에서만 처리

* 모델 로드 오류 
  - 모델 별로

* 알약 인식 오류 
  - 모양, 글자 등 예외 상황 정의 필요

* DB 쿼리 오류
  - 메인 서버 내에서만 처리. 식별과 허가 정보 동일하게 처리 (서버 로그에만 남김)

**Comment by YongSiHun** [comment]
## 비고
* 메인 서버에서 애플리케이션으로 메시지를 내려주는 것이 목적이므로, errCode to msg에 대한 json 파일은 메인서버에서 관리
* 딥러닝 서버에서 발생할 수 있는 오류들을 먼저 정의 후 코드를 정의
* 코드가 정의 되면 메인서버 / 딥러닝 서버 예외처리 작업

**Comment by CaffeinCoding** [comment]
errCode에 관한 내용은 try - except으로 처리 예정
성공 이외의 모든 내용의 return은 isSuccess : false 처리 예정

**Comment by YongSiHun** [comment]
## 서버 간 오류 코드 컨벤션
```
// 런타임 에러
dl-server.runtime.error.

// 일반 에러
dl-server.common.error.
```
* 코드는 kebab case로 정의 (ex) what-is-pill)
* 4층 까지로만 정의하며 필요에 따라 층을 늘릴 수 있음

**Comment by YongSiHun** [comment]
이슈 처리 완료
